// Full list of 150+ apps/utilities for MOOS App Drawer
// Each app has: name, category, icon (CDN or placeholder), and description
export interface AppMeta {
  name: string;
  category: string;
  icon: string;
  description?: string;
}

export const appList: AppMeta[] = [
// Productivity (30)
{ name: 'Calculator', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/calculator.png', description: 'Scientific, Programmer, Currency' },
{ name: 'Calendar', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/calendar.png', description: 'Google Sync, Event Reminders' },
{ name: 'To-Do List', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/todo-list.png', description: 'Kanban Board, Subtasks' },
{ name: 'Notes App', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/note.png', description: 'Markdown, Voice Notes' },
{ name: 'Password Manager', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/password.png', description: 'AES-256 Encryption' },
{ name: 'Spreadsheet', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/ms-excel.png', description: 'Excel-like Formulas' },
{ name: 'PDF Reader/Editor', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/pdf.png', description: 'Annotations, Signatures' },
{ name: 'Flashcards', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/flashcards.png', description: 'Spaced Repetition' },
{ name: 'Pomodoro Timer', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/timer.png', description: 'Work Sessions' },
{ name: 'Project Manager', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/project.png', description: 'Gantt Charts' },
{ name: 'Invoice Generator', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/invoice.png', description: 'Templates' },
{ name: 'Resume Builder', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/resume.png', description: 'AI-Powered' },
{ name: 'Email Client', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/apple-mail.png', description: 'IMAP/POP3' },
{ name: 'Meeting Scheduler', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/meeting.png', description: 'Zoom/Google Meet' },
{ name: 'Clipboard Manager', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/copy.png', description: 'History, Snippets' },
{ name: 'Unit Converter', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/convert.png', description: 'Length, Weight, etc.' },
{ name: 'Recipe Organizer', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/recipe-book.png', description: 'Meal Planner' },
{ name: 'Budget Tracker', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/budget.png', description: 'Expense Analytics' },
{ name: 'Mind Mapping Tool', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/mind-map.png', description: 'Drag-and-Drop Nodes' },
{ name: 'Time Zone Converter', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/worldwide-location.png', description: 'World Clock' },
{ name: 'QR Code Generator/Reader', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/qr-code.png', description: 'QR Code Tools' },
{ name: 'Barcode Scanner', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/barcode.png', description: 'Barcode Tools' },
{ name: 'OCR Tool', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/ocr.png', description: 'Image-to-Text' },
{ name: 'Document Scanner', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/scanner.png', description: 'Webcam Integration' },
{ name: 'eBook Reader', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/ebook.png', description: 'EPUB/PDF' },
{ name: 'Podcast Player', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/podcast.png', description: 'Offline Streaming' },
{ name: 'RSS Feed Aggregator', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/rss.png', description: 'RSS Reader' },
{ name: 'Newsletter Creator', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/news.png', description: 'Newsletter Tools' },
{ name: 'Citation Generator', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/citation.png', description: 'APA/MLA' },
{ name: 'Legal Document Templates', category: 'Productivity', icon: 'https://img.icons8.com/color/96/000000/agreement.png', description: 'Legal Docs' },

// Development (25)
{ name: 'MoCode', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/source-code.png', description: 'Code Editor: Syntax Highlighting, Git, AI Autocomplete' },
{ name: 'MoTerm', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/console.png', description: 'Terminal: SSH, Command History' },
{ name: 'Git Client', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/git.png', description: 'Commit, Branch, Pull Requests' },
{ name: 'API Tester', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/api.png', description: 'REST/GraphQL, Postman-like' },
{ name: 'Database Explorer', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/database.png', description: 'SQLite, MySQL, MongoDB' },
{ name: 'JSON/XML Formatter', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/json.png', description: 'Format JSON/XML' },
{ name: 'Regex Tester', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/regular-expression.png', description: 'Live Preview' },
{ name: 'Web Scraper', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/web-scraper.png', description: 'Cheerio.js Integration' },
{ name: 'Docker Manager', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/docker.png', description: 'Container Dashboard' },
{ name: 'Code Snippet Library', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/code.png', description: 'Searchable' },
{ name: 'UML Diagram Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/uml.png', description: 'UML Diagrams' },
{ name: 'SSL Certificate Checker', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/ssl.png', description: 'SSL Checker' },
{ name: 'Network Speed Tester', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/speed.png', description: 'Speed Test' },
{ name: 'Port Scanner', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/port.png', description: 'LAN Devices' },
{ name: 'Webhook Simulator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/webhook.png', description: 'Webhook Tools' },
{ name: 'JWT Debugger', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/jwt.png', description: 'JWT Debugging' },
{ name: 'Base64 Encoder/Decoder', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/base64.png', description: 'Base64 Tools' },
{ name: 'URL Shortener', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/link.png', description: 'URL Shortening' },
{ name: 'HTTP Status Code Guide', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/http.png', description: 'HTTP Codes' },
{ name: 'CSS Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/css3.png', description: 'Gradients, Shadows' },
{ name: 'SVG Optimizer', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/svg.png', description: 'SVG Tools' },
{ name: 'Color Palette Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/color-palette.png', description: 'Palette Tools' },
{ name: 'Favicon Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/favicon.png', description: 'Favicon Tools' },
{ name: 'Fake JSON API Maker', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/api-settings.png', description: 'Mock API' },
{ name: 'WebAssembly Playground', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/webassembly.png', description: 'WASM Playground' },

// Media (20)
{ name: 'Image Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/image.png', description: 'Crop, Filters, Layers' },
{ name: 'Video Player', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/video.png', description: 'Subtitles, Playlists' },
{ name: 'Music Player', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/music.png', description: 'Playlists, Equalizer' },
{ name: 'Photo Gallery', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/picture.png', description: 'Albums, Tags' },
{ name: 'GIF Maker', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/gif.png', description: 'GIF Creation' },
{ name: 'Screen Recorder', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/screen-recorder.png', description: 'Video/Audio Recording' },
{ name: 'Camera', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/camera.png', description: 'Photo/Video Capture' },
{ name: 'Audio Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/audio-wave.png', description: 'Trim, Effects' },
{ name: 'Podcast Recorder', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/microphone.png', description: 'Record, Edit, Publish' },
{ name: 'Media Converter', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/convert.png', description: 'Audio/Video Formats' },
{ name: 'Streaming Client', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/youtube-live.png', description: 'YouTube, Twitch' },
{ name: 'Slideshow Maker', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/slideshow.png', description: 'Photo Slideshows' },
{ name: 'Meme Generator', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/meme.png', description: 'Create Memes' },
{ name: 'Wallpaper Manager', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/desktop.png', description: 'Auto-Rotate, Download' },
{ name: 'Subtitles Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/subtitles.png', description: 'Sync, Translate' },
{ name: '3D Viewer', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/3d-glasses.png', description: 'View 3D Files' },
{ name: 'Comic Book Reader', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/comic-book.png', description: 'CBR, CBZ Support' },
{ name: 'Music Visualizer', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/visualizer.png', description: 'Audio Visualizations' },
{ name: 'Tag Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/tag-window.png', description: 'Edit MP3/MP4 Tags' },
{ name: 'Voice Changer', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/voice-changer.png', description: 'Live Voice Effects' },
  { name: 'Database Explorer', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/database.png', description: 'SQLite, MySQL, MongoDB' },
  { name: 'JSON/XML Formatter', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/json.png', description: 'Format JSON/XML' },
  { name: 'Regex Tester', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/regular-expression.png', description: 'Live Preview' },
  { name: 'Web Scraper', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/web-scraper.png', description: 'Cheerio.js Integration' },
  { name: 'Docker Manager', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/docker.png', description: 'Container Dashboard' },
  { name: 'Code Snippet Library', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/code.png', description: 'Searchable' },
  { name: 'UML Diagram Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/uml.png', description: 'UML Diagrams' },
  { name: 'SSL Certificate Checker', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/ssl.png', description: 'SSL Checker' },
  { name: 'Network Speed Tester', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/speed.png', description: 'Speed Test' },
  { name: 'Port Scanner', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/port.png', description: 'LAN Devices' },
  { name: 'Webhook Simulator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/webhook.png', description: 'Webhook Tools' },
  { name: 'JWT Debugger', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/jwt.png', description: 'JWT Debugging' },
  { name: 'Base64 Encoder/Decoder', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/base64.png', description: 'Base64 Tools' },
  { name: 'URL Shortener', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/link.png', description: 'URL Shortening' },
  { name: 'HTTP Status Code Guide', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/http.png', description: 'HTTP Codes' },
  { name: 'CSS Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/css3.png', description: 'Gradients, Shadows' },
  { name: 'SVG Optimizer', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/svg.png', description: 'SVG Tools' },
  { name: 'Color Palette Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/color-palette.png', description: 'Palette Tools' },
  { name: 'Favicon Generator', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/favicon.png', description: 'Favicon Tools' },
  { name: 'Fake JSON API Maker', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/api-settings.png', description: 'Mock API' },
  { name: 'WebAssembly Playground', category: 'Development', icon: 'https://img.icons8.com/color/96/000000/webassembly.png', description: 'WASM Playground' },

  // Media (20)
  { name: 'Image Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/image.png', description: 'Crop, Filters, Layers' },
  { name: 'Video Player', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/video.png', description: 'Subtitles, Playlists' },
  { name: 'Music Player', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/music.png', description: 'Playlists, Equalizer' },
  { name: 'Photo Gallery', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/picture.png', description: 'Albums, Tags' },
  { name: 'GIF Maker', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/gif.png', description: 'GIF Creation' },
  { name: 'Podcast Player', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/podcast.png', description: 'RSS, Subscriptions' },
  { name: 'Screen Recorder', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/screen-recorder.png', description: 'Area/Full, Audio' },
  { name: 'Audio Editor', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/audio-wave.png', description: 'Waveform Editing' },
  { name: 'Media Converter', category: 'Media', icon: 'https://img.icons8.com/color/96/000000/convert.png', description: 'Audio/Video Formats' },

// Education (20)
{ name: 'Dictionary', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/book.png', description: 'Word Definitions' },
{ name: 'Thesaurus', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/thesaurus.png', description: 'Synonyms/Antonyms' },
{ name: 'Periodic Table', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/periodic-table.png', description: 'Chemistry Reference' },
{ name: 'Math Solver', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/math.png', description: 'Step-by-Step Math' },
{ name: 'Flashcards', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/flashcards.png', description: 'Study Tool' },
{ name: 'Quiz Maker', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/quiz.png', description: 'Create Quizzes' },
{ name: 'Language Learning', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/language.png', description: 'Vocabulary, Phrases' },
{ name: 'Geography Maps', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/world-map.png', description: 'World Maps' },
{ name: 'Citation Generator', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/citation.png', description: 'APA/MLA' },
{ name: 'Science Experiments', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/science-experiment.png', description: 'DIY Experiments' },
{ name: 'Reading Tracker', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/reading.png', description: 'Track Reading' },
{ name: 'Essay Grader', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/essay.png', description: 'AI Essay Grading' },
{ name: 'Plagiarism Checker', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/plagiarism.png', description: 'Check for Plagiarism' },
{ name: 'Spelling Bee', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/spelling-bee.png', description: 'Word Challenge' },
{ name: 'Timeline Maker', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/timeline.png', description: 'History Timelines' },
{ name: 'Course Planner', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/course-assign.png', description: 'Plan Courses' },
{ name: 'Music Theory', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/music-theory.png', description: 'Learn Music' },
{ name: 'Code Playground', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/code.png', description: 'Practice Coding' },
{ name: 'Flashcard Importer', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/import.png', description: 'Import Flashcards' },
{ name: 'Exam Timer', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/timer.png', description: 'Timed Exams' },
  { name: 'Clipboard History', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/copy.png', description: 'Clipboard Manager' },
  { name: 'Startup Manager', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/rocket.png', description: 'Manage Startup Apps' },
  { name: 'Disk Cleaner', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/broom.png', description: 'Free Up Space' },
  { name: 'Partition Manager', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/hard-drive.png', description: 'Disk Partitions' },
  { name: 'Battery Monitor', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/battery.png', description: 'Battery Health' },
  { name: 'Bluetooth Manager', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/bluetooth.png', description: 'Device Pairing' },
  { name: 'Printer Manager', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/printer.png', description: 'Printer Settings' },
  { name: 'Font Viewer', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/font.png', description: 'Font Preview' },
  { name: 'Archive Extractor', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/zip.png', description: 'ZIP, RAR, 7z' },
  { name: 'Process Explorer', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/process.png', description: 'Detailed Process Tree' },
  { name: 'Hosts File Editor', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/hosts-file.png', description: 'Edit Hosts File' },
  { name: 'Terminal', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/console.png', description: 'Command Line' },
  { name: 'Clipboard Sync', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/sync.png', description: 'Sync Across Devices' },
  { name: 'System Updater', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/update-left-rotation.png', description: 'Check for Updates' },
  { name: 'Power Options', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/shutdown.png', description: 'Sleep, Hibernate, Restart' },
  { name: 'Screen Magnifier', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/magnifier.png', description: 'Zoom Tool' },
  { name: 'Virtual Desktop', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/virtual-machine.png', description: 'Multiple Desktops' },
  { name: 'Accessibility Tools', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/accessibility2.png', description: 'Screen Reader, High Contrast' },
  { name: 'USB Device Manager', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/usb.png', description: 'Manage USB Devices' },
  { name: 'Network Drive Mapper', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/network-drive.png', description: 'Map Drives' },
  { name: 'System Restore', category: 'System Tools', icon: 'https://img.icons8.com/color/96/000000/restore.png', description: 'Restore Points' },

  // Games (20)
  { name: 'Chess', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/chess.png', description: 'Play vs AI or Human' },
  { name: 'Sudoku', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/sudoku.png', description: 'Multiple Levels' },
  { name: 'Minesweeper', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/minesweeper.png', description: 'Classic Puzzle' },
  { name: 'Solitaire', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/solitaire.png', description: 'Klondike, Spider' },
  { name: 'Tetris', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/tetris.png', description: 'Block Puzzle' },
  { name: '2048', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/2048.png', description: 'Addictive Math Game' },
  { name: 'Snake', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/snake.png', description: 'Classic Snake' },
  { name: 'Crossword', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/crossword.png', description: 'Daily Puzzles' },
  { name: 'Memory Match', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/memory-card.png', description: 'Card Matching' },
  { name: 'Word Search', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/word-search.png', description: 'Find Words' },
  { name: 'Checkers', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/checkers.png', description: 'Classic Board Game' },
  { name: 'Mahjong', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/mahjong.png', description: 'Tile Game' },
  { name: 'Backgammon', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/backgammon.png', description: 'Board Game' },
  { name: 'Go', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/go.png', description: 'Strategy Board Game' },
  { name: 'Reversi', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/reversi.png', description: 'Othello' },
  { name: 'Puzzle Slider', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/puzzle.png', description: 'Sliding Puzzle' },
  { name: 'Trivia Quiz', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/quiz.png', description: 'General Knowledge' },
  { name: 'Hangman', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/hangman.png', description: 'Word Guess' },
  { name: 'Mines', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/mine.png', description: 'Bomb Defusal' },
  { name: 'Platformer', category: 'Games', icon: 'https://img.icons8.com/color/96/000000/platformer.png', description: 'Jump & Run' },

  // AI/ML (15)
  { name: 'AI Chatbot', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/chatbot.png', description: 'Conversational AI' },
  { name: 'Image Classifier', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/image-recognition.png', description: 'Classify Images' },
  { name: 'Speech to Text', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/speech-to-text.png', description: 'Voice Recognition' },
  { name: 'Text to Speech', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/text-to-speech.png', description: 'Speech Synthesis' },
  { name: 'Face Detection', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/face-detection.png', description: 'Detect Faces' },
  { name: 'Object Detection', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/object-recognition.png', description: 'Detect Objects' },
  { name: 'Pose Estimation', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/pose-estimation.png', description: 'Body Pose' },
  { name: 'Style Transfer', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/style-transfer.png', description: 'Artistic Filters' },
  { name: 'AI Drawing', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/ai-drawing.png', description: 'Draw with AI' },
  { name: 'Music Generation', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/ai-music.png', description: 'AI Composed Music' },
  { name: 'Text Summarizer', category: 'AI/ML', icon: 'https://img.icons8.com/color/96/000000/summary-list.png', description: 'Summarize Text' },
  { name: 'Quiz Maker', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/quiz.png', description: 'Create Quizzes' },
  { name: 'Language Learning', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/language.png', description: 'Vocabulary, Phrases' },
  { name: 'Geography Maps', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/world-map.png', description: 'World Maps' },
  { name: 'Citation Generator', category: 'Education', icon: 'https://img.icons8.com/color/96/000000/citation.png', description: 'APA/MLA' },

  // Network (20)
  { name: 'WiFi Analyzer', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/wifi.png', description: 'Signal Strength' },
  { name: 'LAN Scanner', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/lan.png', description: 'Find Devices' },
  { name: 'Ping Tool', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/ping.png', description: 'Network Latency' },
  { name: 'Traceroute', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/traceroute.png', description: 'Route Analysis' },
  { name: 'Port Forwarding', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/port-forwarding.png', description: 'Forward Ports' },
  { name: 'Bandwidth Monitor', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/bandwidth.png', description: 'Monitor Usage' },
  { name: 'VPN Manager', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/vpn.png', description: 'VPN Connections' },
  { name: 'Firewall Settings', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/firewall.png', description: 'Manage Firewall' },
  { name: 'Network Map', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/network.png', description: 'Visualize Network' },
  { name: 'Proxy Switcher', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/proxy.png', description: 'Switch Proxies' },
  { name: 'Remote Desktop', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/remote-desktop.png', description: 'Connect Remotely' },
  { name: 'Wake-on-LAN', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/wake-on-lan.png', description: 'Wake Devices' },
  { name: 'Network Speed Test', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/speed.png', description: 'Test Speed' },
  { name: 'Packet Sniffer', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/packet-sniffer.png', description: 'Analyze Packets' },
  { name: 'IP Lookup', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/ip-address.png', description: 'Find IP Info' },
  { name: 'MAC Address Finder', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/mac-address.png', description: 'Find MAC Address' },
  { name: 'Network Logger', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/logger.png', description: 'Log Traffic' },
  { name: 'SSL Checker', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/ssl.png', description: 'SSL Status' },
  { name: 'DNS Lookup', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/dns.png', description: 'DNS Records' },
  { name: 'Network Tools Suite', category: 'Network', icon: 'https://img.icons8.com/color/96/000000/network-toolbar.png', description: 'All-in-One Tools' }
];
